apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-mundo-deployment
  template:
    metadata:
      labels:
        app: hola-mundo-deployment
    spec:
      containers:
      - name: hola-mundo-container
        image: 654654145084.dkr.ecr.us-east-1.amazonaws.com/app_java
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
          requests:
            memory: 128Mi
            cpu: 50m
