apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-java17-service
spec:
  selector:
    app: hola-mundo-java17
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

