apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: test
    spec:
      containers:
      - name: test-service
        image: 654654145084.dkr.ecr.us-east-1.amazonaws.com/my-app-java:v1.0.2
        imagePullPolicy: IfNotPresent
        port:
        - containerPort: 80
