apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-deployment-svc
  namespace: app-java
spec:
  type: LoadBalancer  # Cambiamos el tipo de servicio a LoadBalancer
  selector:
    app: hola-mundo-deployment
  ports:
  - name: http
    protocol: TCP
    port: 8090
    targetPort: 8090
