apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-deployment-svc
  namespace: app-java  # Agregamos el namespace "app-java"
spec:
  type: NodePort
  selector:
    app: hola-mundo-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

