apiVersion: v1
kind: Service
metadata:
  name: hola-mundo-java17-service
spec:
  type: NodePort
  selector:
    app: hola-mundo-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080


